project:
  type: book
  output-dir: docs
  execute-dir: project

book:
  title: "Amostragem e Inferência Estatística"
  author: 
   - Fabio Cop, Unifesp, fcferreira@unifesp.br
  date: last-modified
  cover-image: cover.jpg
  navbar:
    search: false
    background: secondary
    right:
      - icon: github
        href: https://github.com/FCopf
        aria-label: GitHub
  chapters:
    - index.qmd
    - part: qmd/01-amostragem_delineamento/00-PART-amostragemdelineamento.qmd
      chapters:
        - qmd/01-amostragem_delineamento/01-popamostra.qmd
        - qmd/01-amostragem_delineamento/02-amostragem.qmd
    - part: qmd/02-Inferencia_teste_hipoteses/00-PART-inferenciahipoteses.qmd
      chapters:
        - qmd/02-Inferencia_teste_hipoteses/01-norm.qmd
        - qmd/02-Inferencia_teste_hipoteses/02-tcl.qmd
        - qmd/02-Inferencia_teste_hipoteses/03-inferencia.qmd
        - qmd/02-Inferencia_teste_hipoteses/04-testehipot.qmd
        - qmd/02-Inferencia_teste_hipoteses/05-testevar.qmd
        - qmd/02-Inferencia_teste_hipoteses/06-testet.qmd
    
bibliography: references.bib
knitr:
  opts_chunk: 
    echo: true
    message: false
    warning: false

format:
  html:
    theme: cosmo
    code-fold: false
    toc: true
    toc-depth: 2
    code-overflow: wrap


#editor: visual

